name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: 1
    # NOTE
    # Adjust the `input=""` on the last line to indicate where
    # the source of the package page is (`page/` by default).
    #
    # Adjust also `output=""` on the last line if you want
    # the page to be deployed in a specific folder on gh-pages
    # if you do that, make sure that you adjust the `prepath`
    # variable in `config.md` accordingly! so for instance
    # if you set here `folder="web"` change prepath for
    # `@def prepath = "YourPackage.jl/web"`
    - run: julia -e '
            using Pkg;
            Pkg.activate("page/");
            Pkg.add(PackageSpec(url="https://github.com/shashi/FileTrees.jl.git"));
            Pkg.resolve();
            Pkg.add(["NodeJS", "PkgPage", "DataFrames"]);
            using NodeJS;
            run(`$(npm_cmd()) install highlight.js purgecss`);
            import PkgPage;
            PkgPage.optimize(input="page", output="")'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: page/__site
